### ISSUE TITLE
Document better how to use Markdent to convert a markdown dialect to an (X)HTML5 fragment

### ISSUE THREAD

**Issue by shlomif** [houseabsolute/Markdent#15]
Hi,

please document better how to use Markdent to convert a markdown dialect to an (X)HTML5 fragment. I could use a use case complete code fragment somewhere, but my breadcrumbs overflew when trying to see how to do that on metacpan. Furthermore, a commandline app will be nice - http://blogs.perl.org/users/sawyer_x/2010/03/modules-vs-applications.html .

**Comment by autarch** [comment]
There's a `markdent-html` executable that gets installed with the distro, so I think that answers that question. Are you saying you'd like to see the docs address how to do this programmatically as well?

**Comment by autarch** [comment]
I think this is all addressed in [the latest release](https://metacpan.org/release/Markdent).

**Comment by shlomif** [comment]
Many thanks!
