### ISSUE TITLE
Please release a new CPAN version

### ISSUE THREAD

**Issue by shlomif** [houseabsolute/Markdent#20]
Please release a new CPAN version with my https://reproducible-builds.org/ -related changes. If there is anything blocking it, then I'll try to help. Thanks!

**Comment by autarch** [comment]
No blockers, I just forgot to do this. I like to wait until Travis passes, but since that can take a little while I often go do something else and then forget entirely.

**Comment by shlomif** [comment]
@autarch : OK, thanks. Perhaps you can set up a reminder to check travis using https://metacpan.org/pod/App::Countdown and https://metacpan.org/pod/distribution/App-Notifier-Client/bin/notifier or similar.
