### ISSUE TITLE
support reading from stdin

### ISSUE THREAD

**Issue by jonassmedegaard** [houseabsolute/Markdent#23]
Would be nice if markdent-html supported reading content from stdin as is common among markdown parsers.

Most sensible in my opinion would be that if neither `--file` nor `--string` is given then it expects a string from stdin.

More elegantly that could be improved by...

* extend both `--file` and `--string` options to treat value `-` as reading from stdin
* Checking if stdin is tied to a console, and if not then fail with an error that it seems the tool is used wrong (and if above `-` value is supported then suggest to use that to force e.g. for piping in a cron job)

**Comment by autarch** [comment]
I think supporting `--file -` would make sense, as that's a pretty common usage in CLI tools. Supporting `--string -` just seems odd. A PR for just `--file -` would be great!

**Comment by jonassmedegaard** [comment]
Here's a code change that works for me: https://salsa.debian.org/js/libmarkdent-perl/-/commit/1236179849d6277f4de16028b95a67daab88f3bf

(sorry, I won't push code to Github due to their terms of service possibly implicitly watering down copyleft licensing)

**Comment by autarch** [comment]
Thanks, this was added in 0.37.
